/*
 * Raj Shah
 * ICS 4UE
 * August 4, 2023
 * Program description: This program simulates a grade book for a class 
 * with 30 students who each have four test scores. The user can add up to 30
 * students, list the students, calculate their average, and the class average.
 */

/**
 *
 * @author Raj
 */
public class U1A5b extends javax.swing.JFrame {

    /**
     * Creates new form U1A5b
     */
    public U1A5b() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        grade_1 = new javax.swing.JTextField();
        grade_2 = new javax.swing.JTextField();
        grade_3 = new javax.swing.JTextField();
        grade_4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        listBtn = new javax.swing.JButton();
        studentAvgBtn = new javax.swing.JButton();
        courseAvgBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBox = new javax.swing.JTextArea();
        msgBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grades");

        jLabel1.setFont(new java.awt.Font("BiauKaiHK", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Student Grades");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("First Name: ");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Last Name: ");

        lastName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        firstName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        grade_1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        grade_2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        grade_3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        grade_4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Test 2:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Test 1:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Test 3:");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("Test 4:");

        addBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        listBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        listBtn.setText("List");
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });

        studentAvgBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        studentAvgBtn.setText("Student Average");
        studentAvgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAvgBtnActionPerformed(evt);
            }
        });

        courseAvgBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        courseAvgBtn.setText("Course Average");
        courseAvgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseAvgBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        listBox.setEditable(false);
        listBox.setColumns(20);
        listBox.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        listBox.setRows(5);
        jScrollPane1.setViewportView(listBox);

        msgBox.setEditable(false);
        msgBox.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        msgBox.setForeground(new java.awt.Color(0, 51, 204));
        msgBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grade_4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grade_3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grade_2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grade_1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(exitBtn))
                                            .addComponent(listBtn)
                                            .addComponent(addBtn))
                                        .addGap(186, 186, 186))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(studentAvgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(courseAvgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grade_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grade_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grade_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(studentAvgBtn))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listBtn)
                            .addComponent(courseAvgBtn))
                        .addGap(33, 33, 33)
                        .addComponent(exitBtn)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // initialize the array
    String [][] classroom = new String[30][6];
    int index = 0; // increment index depending on array position
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        // get user input
        String firstname = firstName.getText();
        String lastname = lastName.getText();
        String grade1 = grade_1.getText();
        String grade2 = grade_2.getText();
        String grade3 = grade_3.getText();
        String grade4 = grade_4.getText();
        
        // check for empty string
        if (firstname.equals("") || lastname.equals("") || 
                grade1.equals("") || grade2.equals("") || 
                grade3.equals("") || grade4.equals("")) {
            
            msgBox.setText("You left a required piece of information empty.");
            return; // exits the method
        }
        
        try {
            double grade1_d = Double.parseDouble(grade1); // convert to double
            double grade2_d = Double.parseDouble(grade2);
            double grade3_d = Double.parseDouble(grade3);
            double grade4_d = Double.parseDouble(grade4);

            // check if grade is in bounds
            if (grade1_d > 100 || grade1_d < 0 || grade2_d > 100 || grade2_d < 0 
                    || grade3_d > 100 || grade3_d < 0 || grade4_d > 100 || grade4_d < 0) {
                
                msgBox.setText("Please enter a grade between 0-100");
                return; // exits the method
            }
            
            
            if (index > 29) { // max index length is 29
                msgBox.setText("The class is at capacity.");
                return; // exits the function
               
            } 
            for (int i = 0; i < 30; i++) {
                if (firstname.equals(classroom[i][0]) && lastname.equals(classroom[i][1])) {
                    msgBox.setText("Student already exists.");
                    return; // exits the method
                        
                    }
                    
                }
            
            String[] row = {firstname, lastname, grade1, grade2, grade3, grade4}; // add to array
            classroom[index] = row;
            index++; // increment index
            msgBox.setText("Student added!");
                
            
        } catch (Exception e) { // inform user about incorrect input
            msgBox.setText("You must enter a number for the grades.");
        }
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
        listBox.setText(""); // reset text area
        
        // iterate through array
        for (int row = 0; row < index; row++) {           
            String text = classroom[row][0] + " " + classroom[row][1] + ": " + 
                    classroom[row][2] + "% , " + classroom[row][3] + "% , " + 
                    classroom[row][4] + "% , " + classroom[row][5] + "%"; // create text
            
            listBox.append(text + "\n"); // add to text area
        }
    }//GEN-LAST:event_listBtnActionPerformed

    private void studentAvgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAvgBtnActionPerformed
        // TODO add your handling code here:
        String firstname = firstName.getText(); // get input
        String lastname = lastName.getText();
        
        for (int row = 0; row < index; row++) {
            if (firstname.equals(classroom[row][0]) && lastname.equals(classroom[row][1])) { // checks for when first and last name are in array
                double grade1_d = Double.parseDouble(classroom[row][2]); // convert to double
                double grade2_d = Double.parseDouble(classroom[row][3]);
                double grade3_d = Double.parseDouble(classroom[row][4]);
                double grade4_d = Double.parseDouble(classroom[row][5]);
                
                double avg = (grade1_d + grade2_d + grade3_d + grade4_d)/4; // calculates average
                msgBox.setText(firstname + " " + lastname + "'s average is " + avg + "%"); // prints to message box
                return; // exit the method
            }
        
        }
        msgBox.setText("Student does not exist"); // if student doesn't exist
        
    }//GEN-LAST:event_studentAvgBtnActionPerformed

    private void courseAvgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseAvgBtnActionPerformed
        // TODO add your handling code here:
        double sum = 0;
                
        for (int row = 0; row < index; row++) {
            double grade1_d = Double.parseDouble(classroom[row][2]); // convert to double
            double grade2_d = Double.parseDouble(classroom[row][3]);
            double grade3_d = Double.parseDouble(classroom[row][4]);
            double grade4_d = Double.parseDouble(classroom[row][5]);

            sum += (grade1_d + grade2_d + grade3_d + grade4_d); // calculates sum of grades
        }
            
        double avg = sum/(4*index); // calculate average
        msgBox.setText("Course average is " + avg + "%"); // prints to message box
            
    }//GEN-LAST:event_courseAvgBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0); // exit the application
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U1A5b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U1A5b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U1A5b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U1A5b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U1A5b().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton courseAvgBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField grade_1;
    private javax.swing.JTextField grade_2;
    private javax.swing.JTextField grade_3;
    private javax.swing.JTextField grade_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextArea listBox;
    private javax.swing.JButton listBtn;
    private javax.swing.JTextField msgBox;
    private javax.swing.JButton studentAvgBtn;
    // End of variables declaration//GEN-END:variables
}
